# to read byte by byte using seek() and tell()
f = open("data.txt")
print("Before reading: ", f.tell())
s = f.read()
print("After reading: ", f.tell())
f.seek(0)
print("From the beginning again: ", f.tell())
s = f.read(4)
print("First four bytes are: ", s)
print(f.tell())
f.read(3)
print("Next three bytes: ",s)
print(f.tell())
f.close()
input("Press ENTER to exit")
